#pragma once
#include "nrf52840.h"

#define BOARD_NAME "nRF52840-DK"

/* GPIO */
#define GPIO_PORT NRF_P0
#define GPIO_CNF(pin)        (GPIO_PORT->PIN_CNF[(pin)])
#define GPIO_OUTSET_REG      (GPIO_PORT->OUTSET)
#define GPIO_OUTCLR_REG      (GPIO_PORT->OUTCLR)

/* SPIM0 */
#define SPIM                NRF_SPIM0
#define SPIM_CONFIG_REG     (SPIM->CONFIG)
#define SPIM_FREQUENCY_REG  (SPIM->FREQUENCY)
#define SPIM_ENABLE_REG     (SPIM->ENABLE)
#define SPIM_EVENTS_END_REG (SPIM->EVENTS_END)
#define SPIM_TXD_PTR_REG    (SPIM->TXD.PTR)
#define SPIM_TXD_MAXCNT_REG (SPIM->TXD.MAXCNT)
#define SPIM_RXD_PTR_REG    (SPIM->RXD.PTR)
#define SPIM_RXD_MAXCNT_REG (SPIM->RXD.MAXCNT)
#define SPIM_TASKS_START_REG (SPIM->TASKS_START)

#define SPIM_PSEL_SCK_REG   (SPIM->PSEL.SCK)
#define SPIM_PSEL_MOSI_REG  (SPIM->PSEL.MOSI)
#define SPIM_PSEL_MISO_REG  (SPIM->PSEL.MISO)

/* Pins */
#define SCK_PIN  2
#define MOSI_PIN 27
#define MISO_PIN 30
