#pragma once
#include "nrf52840.h"

#define BOARD_NAME "nRF52840-DK"

/* GPIO */
#define GPIO_PORT NRF_P0
#define GPIO_CNF(pin) (GPIO_PORT->PIN_CNF[(pin)])
#define GPIO_OUTSET_REG (GPIO_PORT->OUTSET)
#define GPIO_OUTCLR_REG (GPIO_PORT->OUTCLR)

/* SPIM */
#define SPIM NRF_SPIM0
#define SPIM_CONFIG_REG (SPIM->CONFIG)
#define SPIM_FREQUENCY_REG (SPIM->FREQUENCY)
#define SPIM_ENABLE_REG (SPIM->ENABLE)
#define SPIM_EVENTS_END_REG (SPIM->EVENTS_END)
#define SPIM_EVENTS_STARTED_REG (SPIM->EVENTS_STARTED)
#define SPIM_EVENTS_STOPPED_REG (SPIM->EVENTS_STOPPED)
#define SPIM_ORC_REG (SPIM->ORC)
#define SPIM_TXD_PTR_REG (SPIM->TXD.PTR)
#define SPIM_TXD_MAXCNT_REG (SPIM->TXD.MAXCNT)
#define SPIM_RXD_PTR_REG (SPIM->RXD.PTR)
#define SPIM_RXD_MAXCNT_REG (SPIM->RXD.MAXCNT)
#define SPIM_TASKS_START_REG (SPIM->TASKS_START)
#define SPIM_SHORTS_REG (SPIM->SHORTS)
#define SPIM_INTENCLR_REG (SPIM->INTENCLR)

#define SPIM_PSEL_SCK_REG (SPIM->PSEL.SCK)
#define SPIM_PSEL_MOSI_REG (SPIM->PSEL.MOSI)
#define SPIM_PSEL_MISO_REG (SPIM->PSEL.MISO)

/* UARTE */
#define UARTE NRF_UARTE0
#define UARTE_ENABLE_REG (UARTE->ENABLE)
#define UARTE_CONFIG_REG (UARTE->CONFIG)
#define UARTE_BAUDRATE_REG (UARTE->BAUDRATE)
#define UARTE_TXD_PTR_REG (UARTE->TXD.PTR)
#define UARTE_TXD_MAXCNT_REG (UARTE->TXD.MAXCNT)
#define UARTE_TASKS_STARTTX_REG (UARTE->TASKS_STARTTX)
#define UARTE_TASKS_STOPTX_REG (UARTE->TASKS_STOPTX)
#define UARTE_EVENTS_ENDTX_REG (UARTE->EVENTS_ENDTX)
#define UARTE_EVENTS_TXSTOPPED_REG (UARTE->EVENTS_TXSTOPPED)

#define UARTE_PSEL_TXD_REG (UARTE->PSEL.TXD)
#define UARTE_PSEL_RXD_REG (UARTE->PSEL.RXD)

/* GPIO Pins */
// SPI
#define SCK_PIN 2
#define MOSI_PIN 27
#define MISO_PIN 30
// UARTE
#define TX_PIN 6 // P0.06: UARTE0 TXD -> DK J-Link VCOM RX
#define RX_PIN 8 // P0.08: UARTE0 RXD <- DK J-Link VCOM TX (unused here)
